/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.event.ActionListener;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Muhammad Fahmy
 */
public class v_ADMINSAPI extends javax.swing.JFrame {

    /**
     * Creates new form v_ADMINSAPI
     */
    public v_ADMINSAPI() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnKembali = new javax.swing.JButton();
        btnTambahSapi = new javax.swing.JToggleButton();
        btnHapusSapi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSapi = new javax.swing.JTable();
        cbKandang = new javax.swing.JComboBox<>();
        cbJenisSapi = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(830, 520));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnKembali.setBorder(null);
        btnKembali.setBorderPainted(false);
        btnKembali.setContentAreaFilled(false);
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 690, 160, 50));

        btnTambahSapi.setBorder(null);
        btnTambahSapi.setBorderPainted(false);
        btnTambahSapi.setContentAreaFilled(false);
        getContentPane().add(btnTambahSapi, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 680, 150, 60));

        btnHapusSapi.setBorder(null);
        btnHapusSapi.setBorderPainted(false);
        btnHapusSapi.setContentAreaFilled(false);
        getContentPane().add(btnHapusSapi, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 680, 160, 60));

        tableSapi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableSapi.setToolTipText("");
        tableSapi.setGridColor(new java.awt.Color(255, 255, 255));
        tableSapi.setOpaque(false);
        jScrollPane1.setViewportView(tableSapi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 980, 310));

        cbKandang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        cbKandang.setBorder(null);
        getContentPane().add(cbKandang, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 370, 70));

        cbJenisSapi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        cbJenisSapi.setBorder(null);
        getContentPane().add(cbJenisSapi, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 370, 70));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 370, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uiimages/admin tambah sapi.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_ADMINSAPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_ADMINSAPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_ADMINSAPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_ADMINSAPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_ADMINSAPI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapusSapi;
    private javax.swing.JButton btnKembali;
    private javax.swing.JToggleButton btnTambahSapi;
    private javax.swing.JComboBox<String> cbJenisSapi;
    private javax.swing.JComboBox<String> cbKandang;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tableSapi;
    // End of variables declaration//GEN-END:variables

    public void btnTambah(ActionListener a) {
        btnTambahSapi.addActionListener(a);
    }

    public void btnHapus(ActionListener a) {
        btnHapusSapi.addActionListener(a);
    }

    public void btnKembali(ActionListener a) {
        btnKembali.addActionListener(a);
    }

    public JTable getTableSapi() {
        return tableSapi;
    }

    public void setComboKandang(String[] comboAngkatan) {
        for (String a : comboAngkatan) {
            this.cbKandang.addItem(a);
        }
    }

    public void setComboJenis(String[] comboAngkatan) {
        for (String a : comboAngkatan) {
            this.cbJenisSapi.addItem(a);
        }
    }

    public JComboBox<String> getCbKandang() {
        return cbKandang;
    }

    public JComboBox<String> getCbJenisSapi() {
        return cbJenisSapi;
    }

    public JTextField getUmur() {
        return jTextField1;
    }
    
    

    
}
