/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.event.ActionListener;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Muhammad Fahmy
 */
public class v_ADMINSAPI extends javax.swing.JFrame {

    /**
     * Creates new form v_ADMINSAPI
     */
    public v_ADMINSAPI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTambahSapi = new javax.swing.JToggleButton();
        btnHapusSapi = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSapi = new javax.swing.JTable();
        umurSapi = new javax.swing.JTextField();
        cbKandang = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTambahSapi.setBorder(null);
        btnTambahSapi.setBorderPainted(false);
        btnTambahSapi.setContentAreaFilled(false);
        getContentPane().add(btnTambahSapi, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 120, 50));

        btnHapusSapi.setBorder(null);
        btnHapusSapi.setBorderPainted(false);
        btnHapusSapi.setContentAreaFilled(false);
        btnHapusSapi.setOpaque(false);
        getContentPane().add(btnHapusSapi, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 120, 40));

        btnKembali.setBorder(null);
        btnKembali.setBorderPainted(false);
        btnKembali.setContentAreaFilled(false);
        btnKembali.setOpaque(false);
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 810, 130, 40));

        tableSapi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableSapi.setToolTipText("");
        tableSapi.setEnabled(false);
        jScrollPane1.setViewportView(tableSapi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 420, 400));

        umurSapi.setBorder(null);
        umurSapi.setOpaque(false);
        getContentPane().add(umurSapi, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 210, 30));

        cbKandang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        getContentPane().add(cbKandang, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 210, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SAPI.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 870));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_ADMINSAPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_ADMINSAPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_ADMINSAPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_ADMINSAPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_ADMINSAPI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapusSapi;
    private javax.swing.JButton btnKembali;
    private javax.swing.JToggleButton btnTambahSapi;
    private javax.swing.JComboBox<String> cbKandang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableSapi;
    private javax.swing.JTextField umurSapi;
    // End of variables declaration//GEN-END:variables

    public void btnTambah(ActionListener a) {
        btnTambahSapi.addActionListener(a);
    }

    public void btnHapus(ActionListener a) {
        btnHapusSapi.addActionListener(a);
    }

    public void btnKembali(ActionListener a) {
        btnKembali.addActionListener(a);
    }

    public JTextField getUmurSapi() {
        return umurSapi;
    }

    public JTable getTableSapi() {
        return tableSapi;
    }
    
    public void hapus(){
        umurSapi.setText("");
        cbKandang.setSelectedIndex(0);
    }
    
    public void setComboKandang(String[] comboAngkatan) {
        for (String a : comboAngkatan) {
            this.cbKandang.addItem(a);
        }
    }

    public JComboBox<String> getCbKandang() {
        return cbKandang;
    }
    
}