/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.event.ActionListener;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Muhammad Fahmy
 */
public class v_CRUDPAKAN extends javax.swing.JFrame {

    /**
     * Creates new form v_CRUDPAKAN
     */
    public v_CRUDPAKAN() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        harga = new javax.swing.JTextField();
        persentasePK = new javax.swing.JTextField();
        persentaseBK = new javax.swing.JTextField();
        namaPakan = new javax.swing.JTextField();
        lNamaPakan = new javax.swing.JLabel();
        lBk = new javax.swing.JLabel();
        lPK = new javax.swing.JLabel();
        lTDN = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pakan = new javax.swing.JTable();
        btnKembali = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnUPdate = new javax.swing.JButton();
        persentaseTDN = new javax.swing.JTextField();
        lTDN1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 170, 50));
        getContentPane().add(persentasePK, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 210, 170, 50));
        getContentPane().add(persentaseBK, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 130, 170, 50));
        getContentPane().add(namaPakan, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 170, 50));

        lNamaPakan.setText("NAMA PAKAN");
        getContentPane().add(lNamaPakan, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 90, 30));

        lBk.setText("PERSENTASE BK");
        getContentPane().add(lBk, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, -1, -1));

        lPK.setText("PERSENTASE PK");
        getContentPane().add(lPK, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, -1, -1));

        lTDN.setText("HARGA");
        getContentPane().add(lTDN, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, -1));

        pakan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(pakan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 1010, 290));

        btnKembali.setText("KEMBALI");
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 650, 80, 60));

        btnDelete.setText("HAPUS");
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 640, 80, 60));

        btnTambah.setText("TAMBAH");
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 640, 80, 60));

        btnUPdate.setText("UPDATE");
        getContentPane().add(btnUPdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 640, 80, 60));
        getContentPane().add(persentaseTDN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 130, 170, 50));

        lTDN1.setText("PERSENTASE TDN");
        getContentPane().add(lTDN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 150, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_CRUDPAKAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_CRUDPAKAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_CRUDPAKAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_CRUDPAKAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_CRUDPAKAN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUPdate;
    private javax.swing.JTextField harga;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lBk;
    private javax.swing.JLabel lNamaPakan;
    private javax.swing.JLabel lPK;
    private javax.swing.JLabel lTDN;
    private javax.swing.JLabel lTDN1;
    private javax.swing.JTextField namaPakan;
    private javax.swing.JTable pakan;
    private javax.swing.JTextField persentaseBK;
    private javax.swing.JTextField persentasePK;
    private javax.swing.JTextField persentaseTDN;
    // End of variables declaration//GEN-END:variables

    public void btnHapus(ActionListener a) {
        this.btnDelete.addActionListener(a);
    }

    public void btnKembali(ActionListener a) {
        this.btnKembali.addActionListener(a);
    }

    public void btnTambah(ActionListener a) {
        this.btnTambah.addActionListener(a);
    }

    public void btnUpdate(ActionListener a) {
        this.btnUPdate.addActionListener(a);
    }

    public JTextField getNamaPakan() {
        return namaPakan;
    }

    public JTable getPakan() {
        return pakan;
    }

    public JTextField getPersentaseBK() {
        return persentaseBK;
    }

    public JTextField getPersentasePK() {
        return persentasePK;
    }

    public JTextField getPersentaseTDN() {
        return persentaseTDN;
    }

    public JTextField getHarga() {
        return harga;
    }

    
}
