/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.event.ActionListener;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Muhammad Fahmy
 */
public class v_CRUDPAKAN extends javax.swing.JFrame {

    /**
     * Creates new form v_CRUDPAKAN
     */
    public v_CRUDPAKAN() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        harga = new javax.swing.JTextField();
        persentasePK = new javax.swing.JTextField();
        persentaseBK = new javax.swing.JTextField();
        namaPakan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        pakan = new javax.swing.JTable();
        btnKembali = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnUPdate = new javax.swing.JButton();
        persentaseTDN = new javax.swing.JTextField();
        lTDN1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        harga.setBorder(null);
        harga.setOpaque(false);
        getContentPane().add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 200, 280, 50));

        persentasePK.setBorder(null);
        persentasePK.setOpaque(false);
        getContentPane().add(persentasePK, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 280, 50));

        persentaseBK.setBorder(null);
        persentaseBK.setOpaque(false);
        getContentPane().add(persentaseBK, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 280, 50));

        namaPakan.setBorder(null);
        namaPakan.setOpaque(false);
        getContentPane().add(namaPakan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 280, 50));

        pakan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(pakan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 970, 300));

        btnKembali.setBorder(null);
        btnKembali.setBorderPainted(false);
        btnKembali.setContentAreaFilled(false);
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 680, 160, 60));

        btnDelete.setBorder(null);
        btnDelete.setBorderPainted(false);
        btnDelete.setContentAreaFilled(false);
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 680, 160, 60));

        btnTambah.setBorder(null);
        btnTambah.setBorderPainted(false);
        btnTambah.setContentAreaFilled(false);
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 680, 170, 60));

        btnUPdate.setBorder(null);
        btnUPdate.setBorderPainted(false);
        btnUPdate.setContentAreaFilled(false);
        getContentPane().add(btnUPdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 680, 160, 60));

        persentaseTDN.setBorder(null);
        persentaseTDN.setOpaque(false);
        getContentPane().add(persentaseTDN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 120, 280, 50));

        lTDN1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uiimages/admin jenis pakan1.png"))); // NOI18N
        lTDN1.setText("PERSENTASE TDN");
        getContentPane().add(lTDN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_CRUDPAKAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_CRUDPAKAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_CRUDPAKAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_CRUDPAKAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_CRUDPAKAN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUPdate;
    private javax.swing.JTextField harga;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lTDN1;
    private javax.swing.JTextField namaPakan;
    private javax.swing.JTable pakan;
    private javax.swing.JTextField persentaseBK;
    private javax.swing.JTextField persentasePK;
    private javax.swing.JTextField persentaseTDN;
    // End of variables declaration//GEN-END:variables

    public void btnHapus(ActionListener a) {
        this.btnDelete.addActionListener(a);
    }

    public void btnKembali(ActionListener a) {
        this.btnKembali.addActionListener(a);
    }

    public void btnTambah(ActionListener a) {
        this.btnTambah.addActionListener(a);
    }

    public void btnUpdate(ActionListener a) {
        this.btnUPdate.addActionListener(a);
    }

    public JTextField getNamaPakan() {
        return namaPakan;
    }

    public JTable getPakan() {
        return pakan;
    }

    public JTextField getPersentaseBK() {
        return persentaseBK;
    }

    public JTextField getPersentasePK() {
        return persentasePK;
    }

    public JTextField getPersentaseTDN() {
        return persentaseTDN;
    }

    public JTextField getHarga() {
        return harga;
    }

    
}
