/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import javax.swing.ButtonGroup;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Muhammad Fahmy
 */
public class v_LAPORAN extends javax.swing.JFrame {

    /**
     * Creates new form v_SAPI
     */
    public v_LAPORAN() {
        initComponents();
        this.setLocationRelativeTo(this);
                this.setExtendedState(JFrame.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnKembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSapi = new javax.swing.JTable();
        beratSapi = new javax.swing.JTextField();
        cbNomor = new javax.swing.JComboBox<>();
        umurSapi = new javax.swing.JTextField();
        cbPakan = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        saran = new javax.swing.JTextArea();
        cbVitamin = new javax.swing.JComboBox<>();
        cbVaksin = new javax.swing.JComboBox<>();
        btnHitung = new javax.swing.JButton();
        cek = new javax.swing.JCheckBox();
        cek2 = new javax.swing.JCheckBox();
        lnomor = new javax.swing.JLabel();
        lberat = new javax.swing.JLabel();
        lumur = new javax.swing.JLabel();
        lpakan = new javax.swing.JLabel();
        lvaksin = new javax.swing.JLabel();
        lvitamin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnKembali.setBorder(null);
        btnKembali.setBorderPainted(false);
        btnKembali.setContentAreaFilled(false);
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 440, 100, 30));

        tableSapi.setForeground(new java.awt.Color(255, 255, 255));
        tableSapi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableSapi.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tableSapi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 610, 290));

        beratSapi.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        beratSapi.setEnabled(false);
        getContentPane().add(beratSapi, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 350, 60));

        cbNomor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        getContentPane().add(cbNomor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 350, 50));

        umurSapi.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        umurSapi.setEnabled(false);
        getContentPane().add(umurSapi, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 350, 60));

        cbPakan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        getContentPane().add(cbPakan, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 350, 50));

        saran.setEditable(false);
        saran.setColumns(20);
        saran.setRows(5);
        jScrollPane2.setViewportView(saran);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, 610, 170));

        cbVitamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        cbVitamin.setEnabled(false);
        getContentPane().add(cbVitamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 350, 60));

        cbVaksin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        cbVaksin.setEnabled(false);
        getContentPane().add(cbVaksin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 350, 60));

        btnHitung.setBorder(null);
        btnHitung.setBorderPainted(false);
        btnHitung.setContentAreaFilled(false);
        getContentPane().add(btnHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 620, 270, 60));

        cek.setBorder(null);
        cek.setContentAreaFilled(false);
        getContentPane().add(cek, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 20, 39));

        cek2.setBorder(null);
        cek2.setContentAreaFilled(false);
        getContentPane().add(cek2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, 20, 44));

        lnomor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/peternak-sppk.png"))); // NOI18N
        lnomor.setText("NOMOR SAPI");
        getContentPane().add(lnomor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        lberat.setText("BERAT SAPI");
        getContentPane().add(lberat, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 86, -1, -1));

        lumur.setText("UMUR SAPI");
        getContentPane().add(lumur, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 144, -1, -1));

        lpakan.setText("PAKAN");
        getContentPane().add(lpakan, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 199, -1, -1));

        lvaksin.setText("VAKSIN");
        getContentPane().add(lvaksin, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 349, -1, -1));

        lvitamin.setText("VITAMIN");
        getContentPane().add(lvitamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 274, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_LAPORAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_LAPORAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_LAPORAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_LAPORAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_LAPORAN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField beratSapi;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKembali;
    private javax.swing.JComboBox<String> cbNomor;
    private javax.swing.JComboBox<String> cbPakan;
    private javax.swing.JComboBox<String> cbVaksin;
    private javax.swing.JComboBox<String> cbVitamin;
    private javax.swing.JCheckBox cek;
    private javax.swing.JCheckBox cek2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lberat;
    private javax.swing.JLabel lnomor;
    private javax.swing.JLabel lpakan;
    private javax.swing.JLabel lumur;
    private javax.swing.JLabel lvaksin;
    private javax.swing.JLabel lvitamin;
    private javax.swing.JTextArea saran;
    private javax.swing.JTable tableSapi;
    private javax.swing.JTextField umurSapi;
    // End of variables declaration//GEN-END:variables

    public JTextField getBeratSapi() {
        return beratSapi;
    }

    public JTextArea getSaran() {
        return saran;
    }

    public JTable getTableSapi() {
        return tableSapi;
    }

    public JTextField getUmurSapi() {
        return umurSapi;
    }

    public void setNomorSapi(String[] comboAngkatan) {
        for (String a : comboAngkatan) {
            this.cbNomor.addItem(a);
        }
    }

    public void setMakanan(String[] comboAngkatan) {
        for (String a : comboAngkatan) {
            this.cbPakan.addItem(a);
        }
    }

    public void setVitamin(String[] comboAngkatan) {
        for (String a : comboAngkatan) {
            this.cbVitamin.addItem(a);
        }
    }

    public void setVaksin(String[] comboAngkatan) {
        for (String a : comboAngkatan) {
            this.cbVaksin.addItem(a);
        }
    }

    public JComboBox<String> getCbNomor() {
        return cbNomor;
    }

    public JComboBox<String> getCbPakan() {
        return cbPakan;
    }

    public JComboBox<String> getCbVaksin() {
        return cbVaksin;
    }

    public JComboBox<String> getCbVitamin() {
        return cbVitamin;
    }

    public void check(ItemListener a) {
        this.cbNomor.addItemListener(a);
    }
    
    public void validasi(ItemListener a) {
        this.cek.addItemListener(a);
    }

    public JCheckBox getCek() {
        return cek;
    }
    
    public void validasi2(ItemListener a) {
        this.cek2.addItemListener(a);
    }

    public JCheckBox getCek2() {
        return cek2;
    }
    
    public void btnHitung(ActionListener a){
        btnHitung.addActionListener(a);
    }
    
    public void btnKembali(ActionListener a){
        btnKembali.addActionListener(a);
    }

        
}
