/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.event.ActionListener;
import javax.swing.JFrame;

/**
 *
 * @author Muhammad Fahmy
 */
public class v_NAMAPAKAN extends javax.swing.JFrame {

    /**
     * Creates new form v_NAMAMAKANAN
     */
    public v_NAMAPAKAN() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNamaPakan = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnPakan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNamaPakan.setBorder(null);
        btnNamaPakan.setBorderPainted(false);
        btnNamaPakan.setContentAreaFilled(false);
        getContentPane().add(btnNamaPakan, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 210, 210));

        btnLogout.setBorder(null);
        btnLogout.setBorderPainted(false);
        btnLogout.setContentAreaFilled(false);
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 10, 70, 70));

        btnPakan.setBorder(null);
        btnPakan.setBorderPainted(false);
        btnPakan.setContentAreaFilled(false);
        getContentPane().add(btnPakan, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 260, 220, 210));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/admin-pakan.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_NAMAPAKAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_NAMAPAKAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_NAMAPAKAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_NAMAPAKAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</edibtnLogout>
        //</edibtnLogout>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_NAMAPAKAN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNamaPakan;
    private javax.swing.JButton btnPakan;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public void btnLogout(ActionListener a) {
        this.btnLogout.addActionListener(a);
    }

    public void btnNamaPakan(ActionListener a) {
        this.btnNamaPakan.addActionListener(a);
    }

    public void btnPakan(ActionListener a) {
        this.btnPakan.addActionListener(a);
    }
}
