/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.event.ActionListener;

/**
 *
 * @author Muhammad Fahmy
 */
public class v_PETERNAK extends javax.swing.JFrame {

    /**
     * Creates new form V_PETERNAK
     */
    public v_PETERNAK() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnValidasi = new javax.swing.JButton();
        btnPertumbuhan = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnPenghitung = new javax.swing.JButton();
        peternak = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnValidasi.setBorder(null);
        btnValidasi.setBorderPainted(false);
        btnValidasi.setContentAreaFilled(false);
        getContentPane().add(btnValidasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 90, 90));

        btnPertumbuhan.setBorder(null);
        btnPertumbuhan.setBorderPainted(false);
        btnPertumbuhan.setContentAreaFilled(false);
        getContentPane().add(btnPertumbuhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 100, 130));

        btnLogout.setBorder(null);
        btnLogout.setBorderPainted(false);
        btnLogout.setContentAreaFilled(false);
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 50, 40));

        btnPenghitung.setBorder(null);
        btnPenghitung.setBorderPainted(false);
        btnPenghitung.setContentAreaFilled(false);
        getContentPane().add(btnPenghitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 90, 90));

        peternak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/menu awal peternak.png"))); // NOI18N
        getContentPane().add(peternak, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_PETERNAK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_PETERNAK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_PETERNAK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_PETERNAK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_PETERNAK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPenghitung;
    private javax.swing.JButton btnPertumbuhan;
    private javax.swing.JButton btnValidasi;
    private javax.swing.JLabel peternak;
    // End of variables declaration//GEN-END:variables
    
    public void getBtnLogout(ActionListener a){
        btnLogout.addActionListener(a);
    }
    
    public void getBtnPertumbuhan(ActionListener a){
        btnPertumbuhan.addActionListener(a);
    }
    
    public void getBtnValidasi(ActionListener a){
        btnValidasi.addActionListener(a);
    }
    
    public void getBtnPenghitung(ActionListener a){
        btnPenghitung.addActionListener(a);
    }
    
}
